name: pushandbuild

on: [push, pull_request]

jobs:
    pushandbuild:
        runs-on: ubuntu-latest
        steps:
            - name: checkout code
              uses: actions/checkout@v2
            
            - name: set up docker
              uses: docker/setup-buildx-action@v2
              
            - name: Build Docker server from Docker image
              run: |
                docker build -t my-server-app -f Dockerfile .
      
            - name: Run Server
              run: |
                docker run -d --name my-server -p 3000:3000 my-server-app
      
            - name: Build Testing Docker Image
              run: |
                docker build -t my-testing-app -f Dockerfile.test .
      
            - name: Run Tests
              run: |
                docker run --rm my-testing-app
                
            - name: Stop and Remove Server Container
              run: |
                docker stop my-server
                docker rm my-server
      