name: testbunserver

on: [push, pull_request]

jobs:
    dockercompose:
        runs-on: ubuntu        
        steps:
            - name: checkout code
              uses: actions/checkout@v3
              
            - name: test
              run:
                docker compose run test
